id = "znapper"
name = "znapper"
version = "0.1.0"
schema_version = 1
authors = ["Quaddle <perkins@quaid.me>"]
description = "Take amazing znaps of your code!"
repository = "https://github.com/quyx-org/znapper"
